import { useEffect, useState } from "react";
import Head from "next/head";
import { Navbar } from "@/components";
import { Sidebar } from "@/components";
import { Main } from "@/components";
import { requestAxios } from "@/config/requestAxios";

export default function Home() {
  const [data, setData] = useState([]);
  const [defender, setdefender] = useState(false);

  const getfetchData = () => {
    let token: string | null = "";
    if (typeof window !== "undefined") {
      token = localStorage.getItem("tokencha");
      if (token?.length) {
        token = JSON?.parse(token);
      }
    }
    requestAxios
      .get("/memories/all", { headers: { Authorization: `Token ${token}` } })
      .then((data) => {
        setData(data.data.data);
      })
      .catch((err) => console.log(err));
  };
  useEffect(() => {
    getfetchData();
  }, []);

  useEffect(() => {
    let token: string | null = "";
    if (typeof window !== "undefined") {
      token = localStorage.getItem("tokencha");
      if (token?.length) {
        token = JSON?.parse(token);
        setdefender(true);
      } else {
        window.location.replace("page/login");
      }
    }
  }, []);

  if (defender === false) {
    return;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="background-1"></div>
      <main className="main container">
        <Navbar />
        <div className="d-flex">
          <Sidebar />
          <Main data={data} />
        </div>
      </main>
    </>
  );
}
