import Head from "next/head";
import { Navbar } from "@/components";
import { Sidebar } from "@/components";
import { Main } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main container">
        <Navbar />
        <div className="d-flex">
        <Sidebar />
        <Main/>
        </div>
      </main>
    </>
  );
}
